name: Upload Python Package

on:
  release:
    types: [published]  # Trigger only when a new release is published

jobs:
  upload-to-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write     # Required for trusted publishing
      contents: read      # Required for actions/checkout

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tool
        run: |
          python -m pip install --upgrade pip build

      - name: Build the package
        run: |
          python -m build

      - name: Publish to PyPI via Trusted Publishing
        uses: pypa/gh-action-pypi-publish@release/v1
